# .slather.yml
# $ slather coverage --output-directory HTTPCookieMessageHandler/Reports/Coverage --html --show --scheme HTTPCookieMessageHandler --workspace HTTPCookieMessageHandler.xcworkspace HTTPCookieMessageHandler.xcodeproj
# /Users/v128477/Projects/sandbox/sso/vz-messaging-cookie-handler/ios/HTTPCookieMessageHandler/Example/.slather.yml

coverage_service: html
source_directory: HTTPCookieMessageHandler
xcodeproj: HTTPCookieMessageHandler.xcodeproj
scheme: HTTPCookieMessageHandler
output_directory: HTTPCookieMessageHandlerTests/Reports/Coverage
workspace: HTTPCookieMessageHandler.xcworkspace
ignore:
- "Pods/*"
- "HTTPCookieMessageHandler/Assets/*"
- "HTTPCookieMessageHandlerTests/*"
- "../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/*"
- "../../../../../../Applications/Xcode.app/Contents/Developer/Toolchains/*"
