# .slather.yml
# Generate an HTML coverage report from your CLI, inside the project's root directory:
# $ slather coverage --output-directory build/reports/coverage --html --show --scheme HTTPCookieMessageHandler --workspace HTTPCookieMessageHandler.xcworkspace HTTPCookieMessageHandler.xcodeproj
# xcodebuild -scheme HTTPCookieMessageHandler -workspace HTTPCookieMessageHandler.xcworkspace -showBuildSettings | grep " OBJROOT"

ci_service: travis_ci
# coverage_service: html
coverage_service: coveralls
# build_directory: build
source_directory: HTTPCookieMessageHandler
xcodeproj: HTTPCookieMessageHandler.xcodeproj
workspace: HTTPCookieMessageHandler.xcworkspace
scheme: HTTPCookieMessageHandler
output_directory: build/reports/coverage
verbose: true
xcode_version: 8.3.1
ignore:
  - "Pods/*"
  - "HTTPCookieMessageHandler/Assets/*"
  - "HTTPCookieMessageHandlerTests/*"
  - "../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/*"
  - "../../../../../../Applications/Xcode.app/Contents/Developer/Toolchains/*"
