# .slather.yml
# Generate an HTML coverage report from your CLI, inside the project's root directory:
# $ slather coverage --output-directory HTTPCookieMessageHandler/Reports/Coverage --html --show --scheme HTTPCookieMessageHandler --workspace HTTPCookieMessageHandler.xcworkspace HTTPCookieMessageHandler.xcodeproj

coverage_service: html
source_directory: HTTPCookieMessageHandler
xcodeproj: HTTPCookieMessageHandler.xcodeproj
scheme: HTTPCookieMessageHandler
output_directory: HTTPCookieMessageHandlerTests/Reports/Coverage
workspace: HTTPCookieMessageHandler.xcworkspace
ignore:
- "Pods/*"
- "HTTPCookieMessageHandler/Assets/*"
- "HTTPCookieMessageHandlerTests/*"
- "../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/*"
- "../../../../../../Applications/Xcode.app/Contents/Developer/Toolchains/*"
