sudo: false
language: swift
cache: cocoapods
osx_image: xcode8.3

before_install: rvm install $RVM_RUBY_VERSION
install: bundle install

script:
  - slather setup HTTPCookieMessageHandler.xcodeproj
  - set -o pipefail
  - xcodebuild clean \
     -workspace HTTPCookieMessageHandler.xcworkspace \
     -scheme HTTPCookieMessageHandler \
     -configuration Debug \
     -destination 'platform=iOS Simulator,name=iPhone 4s,OS=9.3' \
     -enableCodeCoverage YES \
     TRAVIS=true \
     build test \
    | xcpretty -f `xcpretty-travis-formatter` --no-utf
  - pod lib lint --quick --allow-warnings

after_success: slather
